[package]
edition = "2021"
name = "day10"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
itertools = "0.12.0"
